// src/routes/cssfabric-modules/[module]/[page]/DocsClassNames.tsx
import cssfabric from "@medyll/cssfabric";
import InnerMenu from "@/components/InnerMenu";

interface IDocsClassNames {
    module: string;
}


export default function DocsClassNames(props: IDocsClassNames) {
    
    const {module,}        = props;
    const moduleAttributes = cssfabric.getModuleDocsAttributes(module);
    // const moduleAttributes = cssfabric.
    
    
    return <div>
        {/*<div className={"flex-v flex-items-end pad-r-8"}>
            <div className={"txt-800 border-b dsp-inline"}>
                cssfabric classnames
            </div>
            <div className={"txt-gray-300 marg-b-4"}>
                generated classnames
            </div>
        </div>*/}
        <div className={"pad-8"}>
            {
                Object.keys(moduleAttributes).map((moduleAttribute: string) => {
                    const newOut = cssfabric.getModuleClassNames.getModuleTagClassNames({module, moduleAttribute});
                    
                    return <div key={moduleAttribute} className={" "}>
                        <h4 className={"pad-tb-2"}>{moduleAttribute}</h4>
                        <div className={"text-gray-400 pad-tb-2"}>
                            {`- cssfabric expressions list for  css ${moduleAttribute} rules`}
                        </div>
                        <div className={"marg-b-8"}>
                            {newOut.map((x: string, y: number) => <div className={""}
                                                        key={x + y}>.{x}</div>)}
                        </div>
                    </div>
                })
            }
        </div>
    </div>
}

// src/components/docs/DocsClassNames.svelte
<script lang="ts">

  import cssfabric from '../../lib/scripts/cssfabric';

  export let module;
  const moduleAttributes = cssfabric.getModuleDocsAttributes(module);

</script>

<div>
    <div class={"flex-v flex-items-end pad-r-4"}>
        <div class={"txt-800 border-b dsp-inline"}>
            cssfabric classnames
        </div>
        <div class={"txt-gray-300 marg-b-1"}>
            generated classnames
        </div>
    </div>
    <div class={"pad"}>
        {#each Object.keys(moduleAttributes) as moduleAttribute  }
            <div>
                <h4 class={"pad-tb"}>{moduleAttribute}</h4>
                <div class={"text-gray-400 pad-tb"}>
                    {`- cssfabric expressions list for  css ${moduleAttribute} rules`}
                </div>
                <div class={"marg-b-8"}>
                    {#each cssfabric.getModuleClassNames.getModuleTagClassNames({module, moduleAttribute}) as className}
                        <div class={""}>.{className}</div>
                    {/each}
                </div>
            </div>
        {/each}
    </div>
</div>
